[package]
name = "author-web"
version = "0.1.0"
authors = ["Sean Burton <seanjburton@gmail.com>"]
edition = "2021"

[features]

[dependencies]
anyhow = "1"
author = { path = "../author" }
cookie = "0.17"
rand = "0.8"
thiserror = "1"
uuid = { version = "1", features = ["v4"] }
